#!/usr/bin/env python3
"""Regenerate registry.yaml from all test files in core/ and community/."""

import pathlib
import re
import sys

try:
    import yaml
except ImportError:
    print("ERROR: pyyaml not installed. Run: pip install pyyaml")
    sys.exit(1)

REPO_ROOT = pathlib.Path(__file__).parent.parent
REGISTRY_PATH = REPO_ROOT / "registry.yaml"
FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)

REGISTRY_FIELDS = ["id", "name", "methodology", "scope", "severity", "clarity", "author", "version"]


def parse_frontmatter(path):
    text = path.read_text()
    m = FRONTMATTER_RE.match(text)
    if not m:
        return None
    try:
        return yaml.safe_load(m.group(1))
    except yaml.YAMLError:
        return None


def main():
    test_files = sorted(
        list(REPO_ROOT.glob("core/**/*.md")) +
        list(REPO_ROOT.glob("community/**/*.md"))
    )
    test_files = [
        f for f in test_files
        if f.name not in {"README.md", "SPEC.md", "CONTRIBUTING.md"}
        and "community/example" not in f.as_posix()
    ]

    entries = []
    errors = []

    for path in test_files:
        fm = parse_frontmatter(path)
        if fm is None:
            errors.append(f"Could not parse: {path.relative_to(REPO_ROOT)}")
            continue
        entry = {"path": str(path.relative_to(REPO_ROOT))}
        for field in REGISTRY_FIELDS:
            if field in fm:
                entry[field] = fm[field]
            else:
                errors.append(f"Missing field '{field}' in {path.relative_to(REPO_ROOT)}")
        entries.append(entry)

    if errors:
        for e in errors:
            print(f"ERROR: {e}")
        sys.exit(1)

    registry = {"tests": entries}
    with open(REGISTRY_PATH, "w") as f:
        f.write("# Research Unit Test Registry\n")
        f.write("# Auto-generated by scripts/registry-build.py — do not edit manually.\n")
        f.write("# Run `python scripts/registry-build.py` to regenerate.\n\n")
        yaml.dump(registry, f, default_flow_style=False, allow_unicode=True, sort_keys=False)

    print(f"Registry updated: {len(entries)} tests written to registry.yaml")


if __name__ == "__main__":
    main()
